### ISSUE TITLE
Add a JSON-feed

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/bryanbraun.github.io#1]
[JSON feed](https://jsonfeed.org/) looks awesome. I should add one to my site. 😄 

I should be able to do this with a template like the one in this project: https://github.com/vallieres/jekyll-json-feed. Ideally, it would be structurally consistent with [my existing feed](https://www.bryanbraun.com/rss.xml) (which contains the full text of the last 10 posts).

**Comment by ajkendal** [comment]
@bryanbraun 

I would like to give this a try, I would also like to try out another issue with your logo as well, but im gonna go at this first

**Comment by bryanbraun** [comment]
Awesome! 🎉

Let me know if you get stuck or have any questions. 😄

**Comment by ajkendal** [comment]
I am just trying to get Jekyll setup right now. , Are you looking for a feed to be located on any page?

**Comment by bryanbraun** [comment]
Maybe we can set it up at `bryanbraun.com/feed.json`? I don't think we need to link to it from anywhere just yet, if that's what you're asking.

**Comment by ajkendal** [comment]
Sounds good. I will get that up tomorrow during the holiday !

**Comment by bryanbraun** [comment]
This has been merged. Thanks for the help!
