### ISSUE TITLE
Ensure the JSON Feed passes the validator

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/bryanbraun.github.io#14]
We just set up [a new JSONFeed](https://github.com/bryanbraun/bryanbraun.github.io/blob/master/_pages/feed.json) (see [jsonfeed.org](https://jsonfeed.org) for details), but I didn't try to validate it until it went online.

Here's the validation report: https://validator.jsonfeed.org/?url=https%3A%2F%2Fwww.bryanbraun.com%2Ffeed.json

It looks like there are a few minor issues we need to fix to make it fully valid.

I think the best way to test it with the validator during local development is with ngrok or some other localtunnel, type solution.

**Comment by ajkendal** [comment]
@bryanbraun 

I will fix that up, i think i see the issue

**Comment by bryanbraun** [comment]
Fixed! See: https://validator.jsonfeed.org/?url=https%3A%2F%2Fwww.bryanbraun.com%2Ffeed.json

Closing this now.
