### ISSUE TITLE
Write a guest blog post

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/bryanbraun.github.io#16]
Write a guest post for my personal blog.

Any topic will work, but the general theme I try to follow is _"bitesized thoughts about the web and the people who use it."_ Some types of post that I've written (and you could write) include:

- Sharing a side project
- Explaining the solution to a technical issue
- Sharing a personal realization related to doing creative or technical work
- Sharing an inspirational quote or passage from something I read or listened to, and a brief thought about it.

It's a jekyll blog. Posts are written in markdown and put in the `_posts` folder. See other posts for examples. The build is over a minute long.

For what it's worth the blog currently averages about 150 visitors a day, and posts go out to about 100 or so subscribers via RSS and email.

_Update: Feel free to submit a post, even if other people have already submitted one. I'm planning on publishing several, and I'll leave this issue open until I'm done accepting them._

**Comment by bryanbraun** [comment]
I got a some great blog submissions from @paniya, @scriptonist, @thibautvs, and @PrajapatiAnkit, which is probably enough for now. Thanks all! I'll merge and publish these over the next month or so.

**Comment by paniya** [comment]
Hi,

Glad you like it. Can you send me the link when you published it. So I can
share it.

*Praneeth Perera*
Undergraduate in University of Colombo School of Computing
IEEEXtreme Country Lead
Member of  ACM
Member of ICASL

Email  : praneethperera24@gmail.com/ praneethperera@ieee.org
Mobile : +94 77 85 89 445

**Comment by bryanbraun** [comment]
@paniya, yeah, I should be able to do that. 😄
