### ISSUE TITLE
Patch vulnerabilities around target="_blank"

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/bryanbraun.github.io#30]
Using `target="_blank"` can open you up to some vulnerabilities, [as described here](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/).

We should address this by adding `rel="noopener noreferrer"` to any links in this codebase using `target="_blank"`.

**Comment by sunpech** [comment]
I'll give this a go.

**Comment by bryanbraun** [comment]
This was merged in https://github.com/bryanbraun/bryanbraun.github.io/pull/31. Thanks again!
