### ISSUE TITLE
Customize the address bar color

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/bryanbraun.github.io#5]
Let's customize the address bar color for iOS and Android, as described here: https://www.themarketingtechnologist.co/change-your-websites-address-bar-to-your-brand-colors/

For the color, lets use `#99ccdd` (the same as the website's top border).

Todo: 
- [x] Customize for iOS
- [x] Customize for Android

**Comment by andresvi94** [comment]
@bryanbraun I'll give this a go

**Comment by bryanbraun** [comment]
Looks great! I've gone ahead and merged it. 👍
